import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic':
          'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
      colors: {
        android: '#3DDC84',
        'ant-design': '#0170FE',
        bitbucket: '#0052CC',
        bootstrap: '#7952B3',
        css: '#1572B6',
        'css-modules': '#000000',
        docker: '#2496ED',
        express: '#000000',
        gcp: '#4285F4',
        git: '#F05032',
        github: '#181717',
        graphql: '#E10098',
        html: '#E34F26',
        ios: '#000000',
        javascript: '#F7DF1E',
        jira: '#0052CC',
        less: '#1D365D',
        'material-design': '#757575',
        mysql: '#4479A1',
        'next-js': '#000000',
        'node-js': '#339933',
        php: '#777BB4',
        postgresql: '#4169E1',
        prisma: '#2D3748',
        react: '#61DAFB',
        'react-native': '#61DAFB',
        redux: '#764ABC',
        remix: '#000000',
        sanity: '#F03E2F',
        sass: '#CC6699',
        sequelize: '#52B0E7',
        shopify: '#7AB55C',
        sketch: '#F7B500',
        storybook: '#FF4785',
        strapi: '#2F2E8B',
        'styled-components': '#DB7093',
        supabase: '#3FCF8E',
        tailwindcss: '#06B6D4',
        typescript: '#3178C6',
        wordpress: '#21759B'
      }
    },
  },
  plugins: [],
  safelist: [
    'bg-android',
    'bg-ant-design',
    'bg-bitbucket',
    'bg-bootstrap',
    'bg-css',
    'bg-css-modules',
    'bg-docker',
    'bg-express',
    'bg-gcp',
    'bg-git',
    'bg-github',
    'bg-graphql',
    'bg-html',
    'bg-ios',
    'bg-javascript',
    'bg-jira',
    'bg-less',
    'bg-material-design',
    'bg-mysql',
    'bg-next-js',
    'bg-node-js',
    'bg-php',
    'bg-postgresql',
    'bg-prisma',
    'bg-react',
    'bg-react-native',
    'bg-redux',
    'bg-remix',
    'bg-sanity',
    'bg-sass',
    'bg-sequelize',
    'bg-shopify',
    'bg-sketch',
    'bg-storybook',
    'bg-strapi',
    'bg-styled-components',
    'bg-supabase',
    'bg-tailwindcss',
    'bg-typescript',
    'bg-wordpress',
  ]
}
export default config
